ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.3.8'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.4.4'
gem "middleman-sprockets", "~> 4.1.1"
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.5.0'
gem 'nokogiri', '~> 1.10.10'
