name: build
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
jobs:
  build-api-docs:
    name: Build API docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.0
        bundler-cache: true
    - run: ./build-api.sh
    # - name: Deploy
    #   if: github.ref == 'refs/heads/staging'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build
    #     cname: bcoin.io
